name: Create image
on: push
jobs:
  build:
    name: Push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          registry: ghcr.io
          repository: nicolaspn/logspout
          tag_with_ref: true
